### ISSUE TITLE
Build errors involving the package

### ISSUE THREAD

**Issue by worntunic** [Nox7atra/Unity-Figma-Gradients#2]
I'm getting build errors when I try to build my project because some of the files of this package contain references to UnityEditor which is not available for builds. I've checked the .asmdefs and:
Packages/com.nox7atra.unity-figma-gradients/Editor/nox7atra.unity-figma-gradients.Editor.asmdef has checked "Any platform" and "Exclude Platforms - Editor"
Packages/com.nox7atra.unity-figma-gradients/Tests/nox7atra.unity-figma-gradients.Tests.asmdef has checked "Any platform"

I think these should either be set to uncheck "Any platform" and check "Include Platforms - Editor" or the scripts should be wrapped in 
`#if UNITY_EDITOR
...
#endif`

Here are the errors I'm getting on build:
Library\PackageCache\com.nox7atra.unity-figma-gradients@b56bd33813\Editor\UIFigmaGradientCustomEditor.cs(8,44): error CS0246: The type or namespace name 'Editor' could not be found (are you missing a using directive or an assembly reference?)
Library\PackageCache\com.nox7atra.unity-figma-gradients@b56bd33813\Editor\UIFigmaGradientCustomEditor.cs(7,2): error CS0246: The type or namespace name 'CustomEditorAttribute' could not be found (are you missing a using directive or an assembly reference?)
Library\PackageCache\com.nox7atra.unity-figma-gradients@b56bd33813\Editor\UIFigmaGradientCustomEditor.cs(7,2): error CS0246: The type or namespace name 'CustomEditor' could not be found (are you missing a using directive or an assembly reference?)
Library\PackageCache\com.nox7atra.unity-figma-gradients@b56bd33813\Editor\UIFigmaGradientCustomEditor.cs(17,26): error CS0115: 'UIFigmaGradientCustomEditor.OnInspectorGUI()': no suitable method found to override
Library\PackageCache\com.nox7atra.unity-figma-gradients@b56bd33813\Tests\Scripts\Editor\Screenshoter.cs(7,6): error CS0246: The type or namespace name 'MenuItemAttribute' could not be found (are you missing a using directive or an assembly reference?)
Library\PackageCache\com.nox7atra.unity-figma-gradients@b56bd33813\Tests\Scripts\Editor\Screenshoter.cs(7,6): error CS0246: The type or namespace name 'MenuItem' could not be found (are you missing a using directive or an assembly reference?)

**Comment by Nox7atra** [comment]
check

**Comment by worntunic** [comment]
Works great, thanks!
